services:
    nginx:
        image: nginx:latest

        volumes:
            - ./nginx-dev-proxy.conf:/etc/nginx/nginx.conf:ro

        ports:
            - 8080:80

    vscode:
        build:
            context: .
            dockerfile: Dockerfile

        environment:
            # Required for the `diesel` CLI to work.
            DATABASE_URL: postgres://postgres:password@postgres/postgres

        volumes:
            # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
            # mounts are relative to the first file in the list, which is a level up.
            - ..:/workspace:cached

        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"
