name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tag
        run: echo "IMAGE_TAG=$(date +%s)-${{ github.sha }}" >> ${GITHUB_ENV}

      - name: Ensure application builds
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: zeroedbooks/web:latest,zeroedbooks/web:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=zeroedbooks/web:latest
          cache-to: type=inline
