name: Publish Package

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/zeroed-books/web

jobs:
  build:
    uses: ./.github/workflows/build.yml
  review:
    uses: ./.github/workflows/review.yml

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    needs:
      - build
      - review

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Download container artifact
        uses: actions/download-artifact@v3
        with:
          name: zeroed-books-web
          path: /tmp

      - name: Load docker image
        run: docker load < /tmp/zeroed-books-web.tar.gz

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          VERSION=$(date +%s)-${{ github.sha }}
          echo IMAGE_NAME=$IMAGE_NAME
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
