name: Review Build

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure application builds
        run: >
          docker build
          --build-arg RELEASE_NAME=${{ github.sha }}
          --file Dockerfile
          .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Check formatting
        run: npm run style:check

      - name: Run tests
        run: npm test -- --coverage

      - uses: codecov/codecov-action@v3
