name: Review Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Ensure application builds
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
